# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [ ]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [ ]:
arr = np.random.random_sample((10, 10)) * 10
print(arr)
print(np.mean(arr))

[[0.38145101 5.57440486 9.43270239 0.7749863  2.97167444 6.49969857
  4.39200168 0.12182803 6.19124103 3.98503677]
 [7.9683559  5.62203205 5.16276087 6.55010179 4.7352942  5.25090498
  5.59952032 3.17183617 7.36648889 9.65436924]
 [2.55866698 2.04285893 2.3213492  8.48575428 4.13700694 2.30501626
  7.18273184 6.08889968 1.03008158 7.42099429]
 [4.83531786 0.0624785  1.36203934 5.4765545  2.21344761 4.19290953
  2.21446567 1.13926738 8.11961879 2.38877341]
 [0.72315835 7.39009373 0.66959682 2.71655899 6.37049232 7.8486569
  8.89408281 6.77862903 8.69979779 7.41315891]
 [6.79043216 6.73275479 5.75095998 1.68102877 2.50203182 2.54039176
  1.09099014 2.20555137 0.79568468 9.30871799]
 [4.718357   7.87135601 2.223009   5.95769562 2.29988197 9.37620608
  0.69332176 6.42318689 6.65098789 0.30092964]
 [4.5582489  8.80770396 0.94839757 8.94087363 1.9760444  1.33058914
  9.61174439 1.06888851 2.55766293 1.86596627]
 [6.02705387 9.88744844 6.20937404 4.50903208 3.47811621 4.25879002
  4.56758912 

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [ ]:
arr1= np.arange(1,16).reshape(3,5).T

In [ ]:
arr2 = arr1[[1,3]]
arr2

array([[ 2,  7, 12],
       [ 4,  9, 14]])

## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [ ]:
def boxarr(n,m):
  arr = np.zeros((n,m))
  arr[0,:] = 1
  arr[-1,:] = 1
  arr[:,0] = 1
  arr[:,-1] = 1
  return arr
boxarr(5,3)

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [ ]:
angleDegrees = np.arange(0,91,15)
angleDegrees

array([ 0, 15, 30, 45, 60, 75, 90])

In [ ]:
angleRadians = np.deg2rad(angleDegrees)
sines = np.sin(angleRadians)
cosines = np.cos(angleRadians)
tangents = np.tan(angleRadians)

## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [ ]:
x=np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
np.diff(x)

array([-2,  3,  3,  3, -4,  6,  2, -9])

## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [ ]:
txt = np.loadtxt("sample.txt")
hist = np.histogram(txt)

(array([ 6, 23, 52, 37, 16, 14, 13, 13, 13, 13]),
 array([-30.58842789, -17.6295851 ,  -4.67074231,   8.28810048,
         21.24694327,  34.20578606,  47.16462884,  60.12347163,
         73.08231442,  86.04115721,  99.        ]))

## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [ ]:
def std_dev(a):
  avg = np.mean(a)
  sum = np.sum((a-avg)**2)
  return np.sqrt(sum/len(a))