# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [ ]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [14]:
arr=np.random.random_sample((10,10))*10
mean=np.mean(arr)
print(arr)
print("Mean:")
print(mean)

[[5.24572432 8.51042256 5.62049819 7.15095176 8.29456747 1.4765435
  4.42104013 0.5008073  4.55800681 5.24756055]
 [7.20635901 8.96029753 9.61982082 9.41280354 9.59207822 4.27781964
  3.66453817 0.63847946 9.86173902 2.30492862]
 [4.81650588 5.37119935 4.72414436 2.56746163 4.25174524 6.07522648
  1.62828733 9.05124245 3.67092357 1.37096214]
 [3.22821796 6.24270276 5.1387609  8.3511124  9.95411381 0.78804384
  4.87376768 3.55566252 5.34450713 7.07336136]
 [2.41733128 1.2599208  2.3217093  6.73671576 4.21648039 1.39509796
  8.05200944 5.65260502 4.42563035 0.53920214]
 [7.96932902 2.03109384 5.69515378 0.31724476 8.61292759 8.61059505
  6.22163882 8.82754144 7.81472434 4.90486868]
 [4.41899519 7.43995027 9.83975355 0.17673441 6.12695608 8.8336284
  9.56027532 3.2106276  7.61754151 4.52173853]
 [2.27748847 5.3031895  1.32707892 7.66721305 9.3018443  1.87442522
  7.24513637 3.96164076 6.87003982 8.10635522]
 [2.98193977 2.11294084 7.60423917 2.58407656 4.01669021 1.92408052
  4.96149239 8

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [16]:
arr = np.arange(1, 16).reshape(5, 3, order='F')
newarr = arr[[1, 3], :]
print(arr)
print("2nd and 4th rows:")
print(newarr)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
2nd and 4th rows:
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [15]:
i,j = 5, 5
arr = np.ones((i,j))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [17]:
angles= np.arange(0, 91, 15)
angles_rad = np.radians(angles)
sine = np.sin(angles_rad)
cosine= np.cos(angles_rad)
tangent= np.tan(angles_rad)
inverse_sine = np.degrees(np.arcsin(sine))
inverse_cosine = np.degrees(np.arccos(cosine))
inverse_tangent = np.degrees(np.arctan(tangent))
print("Angles:", angles)
print("Inverse Sine:", inverse_sine)
print("Inverse Cosine:", inverse_cosine)
print("Inverse Tangent:", inverse_tangent)


Angles: [ 0 15 30 45 60 75 90]
Inverse Sine: [ 0. 15. 30. 45. 60. 75. 90.]
Inverse Cosine: [ 0. 15. 30. 45. 60. 75. 90.]
Inverse Tangent: [ 0. 15. 30. 45. 60. 75. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [18]:
arr = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
differences = np.diff(arr)
print(differences)


[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [19]:
data = np.loadtxt('https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt')
counts, bin_edges = np.histogram(data, bins=10)
for i in range(len(counts)):
    bin_center = (bin_edges[i] + bin_edges[i + 1]) / 2
    print(f"Bin center: {bin_center:.2f}, Count: {counts[i]}")


Bin center: -24.11, Count: 6
Bin center: -11.15, Count: 23
Bin center: 1.81, Count: 52
Bin center: 14.77, Count: 37
Bin center: 27.73, Count: 16
Bin center: 40.69, Count: 14
Bin center: 53.64, Count: 13
Bin center: 66.60, Count: 13
Bin center: 79.56, Count: 13
Bin center: 92.52, Count: 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [20]:
def std(a):
  mean=np.mean(a)
  sum=np.sum((a-mean)**2)
  variance=sum/len(a)
  return np.sqrt(variance)
arr=np.random.random_sample((10))*10
calculated_std=std(arr)
numpy_std=np.std(arr)
print(arr)
print("Calculated std:",calculated_std)
print("Numpy std:",numpy_std)

[1.53699627 2.8094805  2.20734419 8.24369452 7.63121173 6.60172438
 0.36821375 4.68661126 6.93988716 2.57721085]
Calculated std: 2.6775326709365896
Numpy std: 2.6775326709365896
