# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [1]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [ ]:
x=np.random.random_sample((10,10))*10
print(np.mean(x))

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
reshaped=x.reshape(5,3)
print(reshaped)
print(reshaped(1:5:2))

## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [2]:
x=np.ones(5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [14]:
a=np.array([0,15,30,45,60,90])
x=np.radians(a)
sin=np.sin(x)
cos=np.cos(x)
tan=np.tan(x)
print(sin)
print(cos)
print(tan)
isin=np.arcsin(sin)
icos=np.arccos(cos)
itan=np.arctan(tan)
print(np.degrees(isin))
print(np.degrees(icos))
print(np.degrees(itan))

[0.         0.25881905 0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 1.63312394e+16]
[ 0. 15. 30. 45. 60. 90.]
[ 0. 15. 30. 45. 60. 90.]
[ 0. 15. 30. 45. 60. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [5]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
diff=np.diff(x)
print(diff)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [16]:
text = np.loadtxt("/sample.txt")
count,binedges = np.histogram(text)
for i in range(len(count)):
    bincenter=(binedges[i] + binedges[i+1]) / 2
    print("Bin center:{:0.2f}, Count:{:0.2f}".format(bincenter,count[i]))

Bin center:-24.11, Count:6.00
Bin center:-11.15, Count:23.00
Bin center:1.81, Count:52.00
Bin center:14.77, Count:37.00
Bin center:27.73, Count:16.00
Bin center:40.69, Count:14.00
Bin center:53.64, Count:13.00
Bin center:66.60, Count:13.00
Bin center:79.56, Count:13.00
Bin center:92.52, Count:13.00


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [12]:
def newstd(a):
  avg=np.average(a)
  sum=0
  for x in a:
      sum=sum+(x-avg)**2
  std=np.sqrt(sum/len(a))
  print(std)
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newstd(arr)

print(np.std(arr))


2.8722813232690143
2.8722813232690143
