# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [1]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [2]:
np.random.random_sample((10,10))*10
print(np.random.random_sample((10,10))*10)
np.mean(np.random.random_sample((10,10))*10)

[[5.23959287 3.54710568 0.97105028 4.11505923 6.63588227 6.31404332
  8.58802696 3.62733304 3.32630239 5.26152203]
 [6.8889242  2.56112156 9.17029831 1.81012119 4.41493698 1.03154071
  8.19228234 2.8636122  0.04547548 0.31614405]
 [4.88198145 2.53638585 6.43209038 7.46244784 5.21530559 1.80038236
  2.30508849 4.01138782 6.80592942 9.41046298]
 [0.39220189 2.70961115 7.04433962 3.67743677 3.9908283  0.74817586
  8.66011563 8.6959285  9.38133485 0.77104426]
 [0.45851828 6.81247605 5.08089043 2.00424357 1.27547044 1.83336359
  1.73488083 4.33478771 4.31885351 1.8520649 ]
 [9.21356458 9.2955024  4.7151425  2.88775245 3.30974013 7.65244916
  9.70433837 5.88977765 3.61838442 7.01743927]
 [7.2132284  8.01241373 2.91507624 0.30050098 9.21448822 5.57677028
  8.73285775 8.99078997 2.99568735 3.40545044]
 [1.36543166 7.81569215 5.402345   2.72951223 4.91976905 6.28949259
  2.10779505 8.62671094 1.45094841 1.03621111]
 [7.05050611 1.76321151 6.50994625 4.56231722 2.36884277 5.71249229
  6.82915608

4.651861557551387

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [3]:
new_array = np.array([[1,6,11],[2,7,12],[3,8,13],[4,9,14],[5,10,15]])
print(new_array)
print(new_array[1:5:2])

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [5]:
array=np.ones((4,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [7]:

angles = np.array([0,15,30,45,60,75,90])


sin= np.sin(np.radians(angles))
cos = np.cos(np.radians(angles))
tan = np.tan(np.radians(angles))


arcsin = np.degrees(np.arcsin(sin))
arccos = np.degrees(np.arccos(cos))
arctan = np.degrees(np.arctan(tan))



## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [ ]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
print(x)
np.diff(x)

## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [8]:

!wget -nc https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt


data = np.loadtxt('sample.txt')
hist, bin_edges = np.histogram(data)

for i in range(len(hist)):
  bin_center = (bin_edges[i] + bin_edges[i+1]) / 2
  print(f"Bin center: {bin_center:.2f}, Count: {hist[i]}")

--2024-12-09 08:30:45--  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2183 (2.1K) [text/plain]
Saving to: ‘sample.txt’

sample.txt          100%[===================>]   2.13K  --.-KB/s    in 0s      

2024-12-09 08:30:45 (39.3 MB/s) - ‘sample.txt’ saved [2183/2183]

Bin center: -24.11, Count: 6
Bin center: -11.15, Count: 23
Bin center: 1.81, Count: 52
Bin center: 14.77, Count: 37
Bin center: 27.73, Count: 16
Bin center: 40.69, Count: 14
Bin center: 53.64, Count: 13
Bin center: 66.60, Count: 13
Bin center: 79.56, Count: 13
Bin center: 92.52, Count: 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [9]:
array=np.random.random_sample(10)
print(array)
print(np.std(array))
average=np.mean(array)
sum=np.sum((array-average)**2)
print(np.sqrt(sum/len(array)))

[0.69543263 0.14436206 0.43605313 0.84523278 0.1808299  0.07298656
 0.69511983 0.70501864 0.25564152 0.44411253]
0.26220439303138915
0.26220439303138915
