# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [ ]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [ ]:
import numpy as np

array = np.random.random_sample((10, 10)) * 10
average = np.mean(array)

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [ ]:
import numpy as np

array = np.arange(1, 16)
array = array.reshape(3, 5).T
print(array)
new_array = array[[1, 3]]
print(new_array)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [ ]:
import numpy as np

array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [ ]:
import numpy as np


angles_deg = np.arange(0, 91, 15)
angles_rad = np.radians(angles_deg)

sine_values = np.sin(angles_rad)
cosine_values = np.cos(angles_rad)
tangent_values = np.tan(angles_rad)

inverse_sine = np.degrees(np.arcsin(sine_values))
inverse_cosine = np.degrees(np.arccos(cosine_values))
inverse_tangent = np.degrees(np.arctan(tangent_values))

print("Angles (degrees):", angles_deg)
print("Sine values:", sine_values)
print("Cosine values:", cosine_values)
print("Tangent values:", tangent_values)
print("Inverse Sine (degrees):", inverse_sine)
print("Inverse Cosine (degrees):", inverse_cosine)
print("Inverse Tangent (degrees):", inverse_tangent)

Angles (degrees): [ 0 15 30 45 60 75 90]
Sine values: [0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
Cosine values: [1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
Tangent values: [0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
Inverse Sine (degrees): [ 0. 15. 30. 45. 60. 75. 90.]
Inverse Cosine (degrees): [ 0. 15. 30. 45. 60. 75. 90.]
Inverse Tangent (degrees): [ 0. 15. 30. 45. 60. 75. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [ ]:
import numpy as np

x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])

differences = np.diff(x)
print(differences)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [ ]:
import numpy as np
import urllib.request
url = 'https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt'
urllib.request.urlretrieve(url, 'sample.txt')

data = np.loadtxt('sample.txt')
counts, edges = np.histogram(data)

for i in range(len(counts)):
    bin_center = (edges[i] + edges[i + 1]) / 2
    print(f"Bin center: {bin_center}, Count: {counts[i]}")


Bin center: -24.109006493430737, Count: 6
Bin center: -11.150163704648554, Count: 23
Bin center: 1.8086790841336278, Count: 52
Bin center: 14.767521872915811, Count: 37
Bin center: 27.726364661697996, Count: 16
Bin center: 40.68520745048018, Count: 14
Bin center: 53.64405023926236, Count: 13
Bin center: 66.60289302804455, Count: 13
Bin center: 79.56173581682673, Count: 13
Bin center: 92.5205786056089, Count: 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [ ]:
import numpy as np

def custom_std(a):
    mean = sum(a) / len(a)

    squared_differences = [(x - mean) ** 2 for x in a]
    squared_sum = sum(squared_differences)

    variance = squared_sum / len(a)

    std_dev = np.sqrt(variance)

    return std_dev

random_array = np.random.random(100)
custom_result = custom_std(random_array)

builtin_result = np.std(random_array)
print(f"Custom standard deviation: {custom_result}")
print(f"Built-in standard deviation: {builtin_result}")


if np.isclose(custom_result, builtin_result, atol=1e-8):
    print("The custom function matches the built-in function!")
else:
    print("The custom function does not match the built-in function.")


Custom standard deviation: 0.28365108451097276
Built-in standard deviation: 0.28365108451097276
The custom function matches the built-in function!
