# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [1]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [7]:
rand1= np.random.random_sample((10,10))
rand1[:,:]=rand1[:,:]*10
mean=np.mean(rand1)
print(rand1)
print(mean)




[[8.28679086 6.81353522 4.18321091 5.43570768 0.13137114 2.74166267
  1.02263354 2.59892416 2.34918843 9.65777097]
 [2.03786693 0.4962723  4.82397656 7.00343957 7.57852907 7.8655475
  1.26420195 0.08975739 7.68216617 9.23223419]
 [1.69307119 8.73428551 5.84088245 3.96862727 1.28102666 4.44055116
  6.10950797 7.49959734 1.07078605 2.18818107]
 [6.29770844 3.32098082 1.28336359 9.58197119 5.61082182 2.5223279
  1.44754093 5.70887251 6.43939834 1.19663869]
 [3.30812059 1.93190152 3.64030775 0.09739899 6.06701544 3.44188203
  6.152668   5.47366844 3.44014188 8.32579043]
 [0.58340625 6.68427374 7.12253698 2.66079238 9.82140598 4.33676243
  8.37094161 6.66313644 5.2875407  8.87200497]
 [5.65107807 1.27747208 6.75293797 2.34042926 8.78701863 7.08334216
  1.37105824 1.49268018 3.09979382 6.35267638]
 [0.95945489 1.02664532 3.49705364 0.16964893 2.32425844 3.83724886
  0.36650687 0.30356292 5.83500494 6.41024356]
 [0.83496861 3.27515386 8.10500063 6.15007971 4.37491524 2.93629305
  9.76346757 3

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [13]:
list1=[1,6,11]
list2 =[]
list3 =[]
list4 =[]
list5 =[]

for i in range(3):
  list2.append(list1[i]+1)
  list3.append(list1[i]+2)
  list4.append(list1[i]+3)
  list5.append(list1[i]+4)

a=np.array([list1,list2,list3,list4,list5])
print(a)
print(a[1:4:2])



[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [24]:
r=input("number of rows ")
c=input("number of columns ")
a=np.ones([int(r),int(c)])
b=np.zeros([((int(r)-2)),((int(c)-2))])
a[1:(int(r)-1),1:(int(c)-1)]=b
print(a)


number of rows 4
number of columns 5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [25]:
a=np.array([0,15,30,45,60,75,90])
b=np.sin(np.deg2rad(a))
c=np.cos(np.deg2rad(a))
d=np.tan(np.deg2rad(a))
print(b)
print(c)
print(d)
e=np.arcsin(b)
f=np.arccos(c)
g=np.arctan(d)
print(np.rad2deg(e))
print(np.rad2deg(f))
print(np.rad2deg(g))

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [26]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
print(np.diff(x))

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [32]:
data=np.loadtxt("numpysample.txt")
hist,bin_edges=np.histogram(data)
for i in range(len(hist)):
  print("Bin centre= "+ str(bin_edges[i]+(bin_edges[i+1]-bin_edges[i])/2))
  print("Bin Count= "+ str(hist[i]))

Bin centre= -24.109006493430737
Bin Count= 6
Bin centre= -11.150163704648554
Bin Count= 23
Bin centre= 1.8086790841336278
Bin Count= 52
Bin centre= 14.767521872915811
Bin Count= 37
Bin centre= 27.726364661697996
Bin Count= 16
Bin centre= 40.68520745048018
Bin Count= 14
Bin centre= 53.64405023926236
Bin Count= 13
Bin centre= 66.60289302804455
Bin Count= 13
Bin centre= 79.56173581682673
Bin Count= 13
Bin centre= 92.5205786056089
Bin Count= 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [37]:

lst = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst.append(ele)
mean=np.mean(lst)
sos=[]
for i in range(0, n):
  sq=(lst[i]-mean)**2
  sos.append(sq)

var=np.sum(sos)/n
std=np.sqrt(var)
print(std)
stdcheck=np.std(lst)
print(stdcheck)




Enter number of elements : 3
5
6
7
0.816496580927726
0.816496580927726
