# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [3]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [4]:
random_array = np.random.random_sample((10, 10)) * 10
average = np.mean(random_array)
print(average)

4.995293871176105


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(5,3,order='F')
print(arr)
filter_arr = [False,True,False,True,False]
new_arr = arr[filter_arr]
print(new_arr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [ ]:
import numpy as np
def create_border_array(rows, cols):
    arr = np.zeros((rows, cols),dtype=int)
    arr[0,:] = 1
    arr[3,:] = 1
    arr[:,0] = 1
    arr[:,4] = 1
    return arr
arr = create_border_array(4, 5)
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [ ]:
angles_deg = np.arange(0, 91, 15)
angles_rad = np.radians(angles_deg)
sine_values = np.sin(angles_rad)
cosine_values = np.cos(angles_rad)
tangent_values = np.tan(angles_rad)
inverse_sine = np.degrees(np.arcsin(sine_values))
inverse_cosine = np.degrees(np.arccos(cosine_values))
inverse_tangent = np.degrees(np.arctan(tangent_values))

## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [ ]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
differences = np.diff(x)
print(differences)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [ ]:
import numpy as np
url = "https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt"
data = np.loadtxt(url)
counts, bin_edges = np.histogram(data, bins=5)
for i in range(len(counts)):
    bin_center = (bin_edges[i] + bin_edges[i+1]) / 2  # Calculate bin center
    print(f"Bin center: {bin_center:.2f}, Count: {counts[i]}")


Bin center: -17.63, Count: 29
Bin center: 8.29, Count: 89
Bin center: 34.21, Count: 30
Bin center: 60.12, Count: 26
Bin center: 86.04, Count: 26


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [ ]:
def custom_std(a):
    mean_a = np.mean(a)
    squared_diff = (a - mean_a) ** 2
    sum_squared_diff = np.sum(squared_diff)
    variance = sum_squared_diff / len(a)
    return np.sqrt(variance)
a = np.random.rand(10)
print("Array:", a)
custom_std_value = custom_std(a)
numpy_std_value = np.std(a)
print("\nCustom Standard Deviation:", custom_std_value)

Array: [0.60092126 0.26125487 0.00234319 0.34455717 0.19066859 0.40127546
 0.74369348 0.88978713 0.87451217 0.87033239]

Custom Standard Deviation: 0.30495098517416663
