Question 1

In [1]:
import numpy as np

In [2]:
random_array = np.random.rand(10, 10) * 10

In [3]:
average=np.mean(random_array)

In [4]:
random_array

array([[0.04580131, 4.4601689 , 6.22861696, 8.56029814, 3.6306706 ,
        5.95695899, 4.55082763, 0.20826949, 6.42728201, 1.66055656],
       [6.2636555 , 3.95252112, 8.32622   , 2.67174203, 5.43589704,
        1.39201547, 8.3427791 , 0.99218505, 2.72764699, 5.44764732],
       [0.59728837, 5.00002228, 8.32686622, 9.12075811, 0.87317571,
        3.7300884 , 7.59394341, 3.44496146, 9.33745316, 7.10248955],
       [5.24822934, 5.31488101, 5.19983218, 5.21043863, 9.21507415,
        7.10210015, 4.44436695, 9.82558175, 3.69482222, 0.12745448],
       [8.2716636 , 2.06169093, 8.66021793, 5.88064226, 3.20238844,
        3.43210574, 9.50158443, 7.42534056, 9.90589381, 2.73966475],
       [5.3728769 , 6.71957442, 6.76931776, 0.74365483, 3.23462963,
        5.78419253, 4.38477313, 1.53367458, 4.31018098, 8.73518612],
       [8.99935572, 4.73720537, 7.46467082, 1.88497073, 2.67253254,
        2.77153415, 0.03596628, 4.59306694, 1.94500092, 9.47986388],
       [3.56346633, 8.3069102 , 0.9749642

In [5]:
average

4.838808277987578

Question 2

In [6]:
array=np.arange(1,16)

In [7]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
array =array.reshape(3,5)

In [17]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
array_2=array.T
array_2

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [20]:
new_array = array[[1, 2], :]

In [21]:
new_array

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Question 3

In [23]:
array =np.zeros((4,5),dtype=int)

In [24]:
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
array[0,:] =1

In [27]:
array[-1,:]=1

In [28]:
array

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [29]:
array[:,0]=1

In [30]:
array[:,-1]=1

In [31]:
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Question 4

In [32]:
angles=np.arange(0,91,15)

In [33]:
angles

array([ 0, 15, 30, 45, 60, 75, 90])

In [35]:
angles_rad=np.deg2rad(angles)

In [38]:
sinv=np.sin(angles_rad)
cosv=np.cos(angles_rad)
tanv=np.tan(angles_rad)


In [39]:
sinv

array([0.        , 0.25881905, 0.5       , 0.70710678, 0.8660254 ,
       0.96592583, 1.        ])

In [40]:
cosv

array([1.00000000e+00, 9.65925826e-01, 8.66025404e-01, 7.07106781e-01,
       5.00000000e-01, 2.58819045e-01, 6.12323400e-17])

In [41]:
tanv

array([0.00000000e+00, 2.67949192e-01, 5.77350269e-01, 1.00000000e+00,
       1.73205081e+00, 3.73205081e+00, 1.63312394e+16])

Question 5

In [42]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])

In [43]:
diff=np.diff(x)

In [44]:
diff

array([-2,  3,  3,  3, -4,  6,  2, -9])

Question 6

In [46]:
data=np.loadtxt('/content/sample.txt')

In [47]:
data

array([[ 0.00000000e+00, -4.75677275e+00],
       [ 1.00000000e+00,  6.88953354e+00],
       [ 2.00000000e+00,  8.99689609e+00],
       [ 3.00000000e+00, -1.74610171e+00],
       [ 4.00000000e+00,  1.03044029e+00],
       [ 5.00000000e+00,  4.63576843e+00],
       [ 6.00000000e+00,  5.17722592e+00],
       [ 7.00000000e+00,  1.59646902e+01],
       [ 8.00000000e+00, -1.20210982e+01],
       [ 9.00000000e+00, -1.81008788e+01],
       [ 1.00000000e+01, -2.51788866e+01],
       [ 1.10000000e+01,  4.51892535e+00],
       [ 1.20000000e+01,  9.04391677e+00],
       [ 1.30000000e+01, -5.22153591e-01],
       [ 1.40000000e+01, -3.13388866e+00],
       [ 1.50000000e+01, -6.91471494e+00],
       [ 1.60000000e+01, -6.31426355e+00],
       [ 1.70000000e+01,  6.70690189e+00],
       [ 1.80000000e+01, -2.59716364e+01],
       [ 1.90000000e+01, -4.43537243e+00],
       [ 2.00000000e+01,  4.88905016e-01],
       [ 2.10000000e+01, -3.60048108e-02],
       [ 2.20000000e+01, -4.37254566e+00],
       [ 2.

In [48]:
counts, edges = np.histogram(data)

In [54]:
for i in range(len(counts)):
  bin_center = (edges[i] + edges[i + 1]) / 2


In [56]:
bin_center

92.5205786056089

Question 7

In [69]:
def my_std(a):
 avg=np.mean(a)
 sum_sq_diff=np.sum(((a-avg)**2))
 std_dev=np.sqrt(sum_sq_diff/(len(a)))
 return std_dev

In [73]:
random_array = np.random.rand(10)


In [74]:
random_array

array([0.97734896, 0.93794481, 0.91679368, 0.37217866, 0.16660622,
       0.39224353, 0.66525817, 0.56110715, 0.97658446, 0.99030135])

In [75]:
my_std_result = my_std(random_array)
numpy_std_result = np.std(random_array)

In [76]:
if my_std_result==numpy_std_result:
  print("The results are equal")
else:
  print("The results are not equal")


The results are equal
