# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [2]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [3]:
random_arr = np.random.random_sample((10,10))*10
average= np.mean(random_arr)
print(random_arr)
print(average)


[[4.2868557  0.78302664 5.33731345 7.44325227 0.95477424 9.75500251
  1.08521326 9.76149555 6.22446291 6.57139786]
 [8.97252559 3.56411073 3.83827674 8.29610732 9.2461536  0.62366102
  0.14144419 3.45808486 5.06968697 3.84925706]
 [2.14606926 6.59158051 7.31642393 5.43924508 1.825721   2.55108
  8.72992993 1.38857035 1.27327729 8.9884612 ]
 [4.55861887 7.17021838 4.10508893 7.43764204 8.24176399 5.79147337
  2.51311299 7.99187708 1.1477582  0.67780752]
 [3.50580777 1.14282639 5.81417266 0.64154441 6.3314189  6.62185328
  2.3475471  6.18832031 1.09495677 5.74502924]
 [7.83997662 6.764204   7.3883012  3.19350835 2.69549175 8.90383877
  6.22152376 4.78432248 5.48169995 0.3141184 ]
 [1.10315423 1.04321355 2.3882428  0.61058048 5.44975153 4.63464387
  8.57765983 2.83977715 6.33383667 4.54102216]
 [7.77324707 5.35038724 6.41508762 3.71252968 3.40474968 7.64727062
  4.24357435 6.49245824 1.25216653 8.70523841]
 [2.64301303 2.65338429 2.07727258 4.02703054 7.32775346 7.29899316
  9.59147533 7.

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [4]:
arr = np.arange(1,16).reshape(5,3)
print(arr)
print(arr[[1,3], :])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 4  5  6]
 [10 11 12]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [5]:
row = int(input())
coloumn = int(input())
arr = np.ones((row,coloumn),dtype = int)
arr[1:-1,1:-1] = 0
print(arr)

KeyboardInterrupt: Interrupted by user

## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [6]:
arr = np.arange(0,91,15)

print(arr)
sin = np.sin(np.radians(arr))
print(sin)
cos = np.cos(np.radians(arr))
print(cos)
tan = np.tan(np.radians(arr))
print(tan)
asin = np.arcsin(sin)
print(np.degrees(asin))
acos = np.arccos(cos)
print(np.degrees(acos))
atan = np.arctan(tan)
print(np.degrees(atan))


[ 0 15 30 45 60 75 90]
[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]
[ 0. 15. 30. 45. 60. 75. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [7]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
diff = np.diff(x)
print(diff)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [10]:
import urllib.request
url = 'https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt'
urllib.request.urlretrieve(url, 'sample.txt')

data = np.loadtxt('sample.txt')
counts, edges = np.histogram(data)

for i in range(len(counts)):
    bin_center = (edges[i] + edges[i + 1]) / 2
    print(f"Bin center: {bin_center}, Count: {counts[i]}")


Bin center: -24.109006493430737, Count: 6
Bin center: -11.150163704648554, Count: 23
Bin center: 1.8086790841336278, Count: 52
Bin center: 14.767521872915811, Count: 37
Bin center: 27.726364661697996, Count: 16
Bin center: 40.68520745048018, Count: 14
Bin center: 53.64405023926236, Count: 13
Bin center: 66.60289302804455, Count: 13
Bin center: 79.56173581682673, Count: 13
Bin center: 92.5205786056089, Count: 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [12]:

def custom_std(a):
    mean = sum(a) / len(a)

    squared_differences = [(x - mean) ** 2 for x in a]
    squared_sum = sum(squared_differences)

    variance = squared_sum / len(a)

    std_dev = np.sqrt(variance)

    return std_dev

random_array = np.random.random(100)
custom_result = custom_std(random_array)

builtin_result = np.std(random_array)
print(f"Custom standard deviation: {custom_result}")
print(f"Built-in standard deviation: {builtin_result}")


if np.isclose(custom_result, builtin_result, atol=1e-8):
    print("The custom function matches the built-in function!")
else:
    print("The custom function does not match the built-in function.")

Custom standard deviation: 0.298088678093145
Built-in standard deviation: 0.298088678093145
The custom function matches the built-in function!
