# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [2]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [4]:
arr=np.array(10*np.random.random_sample((10, 10)))
mean=np.mean(arr)
print(arr)
print(mean)

[[3.35596839 2.8509849  2.83168145 1.71164906 3.51257746 4.95471372
  3.71314344 5.03808678 6.03833289 3.34062275]
 [6.32766483 9.62302195 7.46678792 8.55372613 7.80161132 7.86793731
  8.57489219 4.51624677 1.0935013  5.79247534]
 [3.01256865 2.68591057 2.97641538 8.8828229  3.64198298 9.91460032
  0.81070057 1.25845111 6.07766608 7.84253465]
 [6.80905568 4.28210111 7.94945454 4.16782759 5.74462692 3.10735033
  3.72192704 9.9303264  0.66921687 4.69625616]
 [8.05721057 6.56222733 5.53639498 2.2869231  0.744182   4.01219831
  7.1553412  5.04088693 3.64220857 1.8525871 ]
 [1.64021798 8.93521542 4.46358167 6.58207332 0.42986599 7.19066776
  1.83387087 0.4597626  2.5988696  6.99943611]
 [6.76540017 8.82842914 7.62777456 9.23959905 0.44012515 3.73579313
  0.80260853 6.2690372  7.5807089  6.17528279]
 [7.55853337 0.85698732 3.12071583 3.40287361 9.64964262 4.80515898
  8.78074451 0.15644891 5.91302878 2.18211115]
 [9.56973926 6.01160976 9.61857676 9.27162262 6.19485654 4.60896215
  3.85530258

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [39]:
arr=np.array([])
for x in range(1,16):
    arr=np.append(arr, x)
arr=arr.reshape(3,5)
arr=np.dstack(arr)
arr=arr.reshape(5,3)
arr=np.array(arr, dtype=(int))
arr_new=np.stack((arr[1], arr[3]))
print(arr, '\n')
print(arr_new)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]] 

[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [32]:
arr=np.ones((5,5))
arr[1:-1, 1:-1]=0
arr=np.array(arr, dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [26]:
import math
arr=np.array([0,15,30,45,60,75,90])
arr_rad=arr*math.pi/180
sin_array=np.sin(arr_rad)
cos_array=np.cos(arr_rad)
tan_array=np.tan(arr_rad)
inverse_sin=np.arcsin(sin_array)*180/math.pi
inverse_cos=np.arccos(cos_array)*180/math.pi
inverse_tan=(np.arctan(tan_array))*180/math.pi
print(sin_array)
print(inverse_sin,'\n\n')
print(cos_array)
print(inverse_cos,'\n\n')
print(tan_array)
print(inverse_tan,'\n\n')


[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[ 0. 15. 30. 45. 60. 75. 90.] 


[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[ 0. 15. 30. 45. 60. 75. 90.] 


[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[ 0. 15. 30. 45. 60. 75. 90.] 




## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [18]:
x=np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
y=np.diff(x)
print(y)

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [47]:
arr=np.loadtxt("/content/sample.txt")
arr_hist=np.histogram(arr)
print(arr_hist)
for x in range(len(arr_hist[1])-1):
  print((arr_hist[1][x]+arr_hist[1][x+1])/2, arr_hist[0][x])

(array([ 6, 23, 52, 37, 16, 14, 13, 13, 13, 13]), array([-30.58842789, -17.6295851 ,  -4.67074231,   8.28810048,
        21.24694327,  34.20578606,  47.16462884,  60.12347163,
        73.08231442,  86.04115721,  99.        ]))
-24.109006493430737 6
-11.150163704648554 23
1.8086790841336278 52
14.767521872915811 37
27.726364661697996 16
40.68520745048018 14
53.64405023926236 13
66.60289302804455 13
79.56173581682673 13
92.5205786056089 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [59]:
n=int(input("Enter the number of elements: "))
arr=np.array([])
for x in range(n):
  arr=np.append(arr, int(input(f"Enter the element {x+1}: ")))
mean=np.mean(arr)
subtract_square_arr=np.array([])
for y in range(n):
  subtract_square_arr=np.append(subtract_square_arr, (arr[y]-mean)**2)
sum_arr=np.sum(subtract_square_arr)/n
standard_dev=np.sqrt(sum_arr)
print(standard_dev)
print(np.std(arr))
if standard_dev==np.std(arr):
  print("Code is corret")



Enter the number of elements: 3
Enter the element 1: 4
Enter the element 2: 5
Enter the element 3: 3
0.816496580927726
0.816496580927726
Code is corret
