# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [31]:
import numpy as np
import matplotlib.pyplot as plt


## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [32]:
import numpy as np
a1 = np.random.random_sample(size=(10,10))
a2 = a1 * 10
mean = np.mean(a2)
print(mean)
print(a2)





5.280971685148184
[[1.04328495 1.90848558 8.09211001 7.86663537 9.23884394 5.90897215
  2.26668881 4.80854482 0.64095701 8.39111263]
 [0.06299865 9.31286895 9.26740541 1.07415963 3.823959   4.32310184
  5.97215468 9.52854553 9.32512002 7.01688362]
 [5.37703801 5.99491644 3.35600279 8.56526741 3.7992334  4.15516491
  2.85416568 8.61101279 3.86789702 8.4897145 ]
 [3.10524062 6.66378645 7.84237675 8.1230387  8.951186   9.69873939
  8.85616339 1.21896117 1.58728624 4.13112348]
 [6.79275568 5.55391252 3.16026457 3.38385035 5.78072628 9.47521417
  8.711041   8.92298473 1.25894812 6.50143577]
 [7.53036824 8.11003025 3.78076746 4.72308147 6.33020475 5.28011848
  6.81608423 3.6962493  7.82997446 6.74682248]
 [0.76708772 1.65109457 8.5641662  7.99894034 2.8191907  5.80168276
  7.18465698 1.32335238 3.34965501 1.01215716]
 [9.08113535 3.53339831 8.49440877 2.55854768 5.84578961 7.89472478
  5.64934264 0.07245412 2.3633146  4.73907503]
 [3.8123301  0.32363692 1.00605363 7.66670058 1.5888983  0.680

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [33]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a3 = np.array([11,12,13,14,15]).reshape(5,1)
print(a3)
a4 = np.stack((a1,a2),axis = 1)
a5 = np.concatenate((a4,a3),axis = 1)
print(a5)



[[11]
 [12]
 [13]
 [14]
 [15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [34]:
import numpy as np
rows = int(input("enter the number of rows: "))
columns = int(input("emter the number of columns: "))
ar = np.zeros(rows * columns)
ar2 = ar.reshape(rows,columns)
for i in range(0,rows):
  for j in range(0,columns):
    if i == 0 or i == rows - 1:
      ar2[i,j] = 1
    elif j == 0 or j == columns - 1:
      ar2[i,j] = 1
    else:
      ar2[i,j] = 0
print(ar2)



[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [35]:
ar = np.zeros(7)
for i in range(0,7):
  ar[i] = 15 * i
a2 = (np.pi/180)*ar
print(a2)
raysin = np.sin(a2)
raycos = np.cos(a2)
raytan = np.tan(a2)
s = np.arcsin(raysin)
c = np.arccos(raycos)
t = np.arctan(raytan)
print(raysin)
print(raycos)
print(raytan)
print(s)
print(c)
print(t)


[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [36]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
columns = x.shape[0]
for i in range(0,columns-1):
  print(x[i]-x[i+1])

2
-3
-3
-3
4
-6
-2
9


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [37]:
sample = np.loadtxt("sample.txt")
data = sample[::,1]
hist, bin_edges = np.histogram(data, bins = 10)
print(hist,bin_edges)

center = []
for i in range(0,len(bin_edges)-1):
    bin_center = (bin_edges[i]+bin_edges[i+1])/2
    center.append(bin_center)
center_count = []
for i in range(0,len(center)):
    center_count.append((center[i],hist[i]))
print(center_count)
    









[ 3  4  9 22 22 22  9  7  1  1] [-30.58842789 -23.67009726 -16.75176662  -9.83343599  -2.91510536
   4.00322527  10.9215559   17.83988653  24.75821717  31.6765478
  38.59487843]
[(np.float64(-27.129262572005736), np.int64(3)), (np.float64(-20.21093194037355), np.int64(4)), (np.float64(-13.29260130874136), np.int64(9)), (np.float64(-6.374270677109173), np.int64(22)), (np.float64(0.5440599545230143), np.int64(22)), (np.float64(7.462390586155202), np.int64(22)), (np.float64(14.38072121778739), np.int64(9)), (np.float64(21.299051849419577), np.int64(7)), (np.float64(28.217382481051764), np.int64(1)), (np.float64(35.135713112683945), np.int64(1))]


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [38]:
from math import sqrt
def std(a):
  mean = np.mean(a)
  sum = 0
  for i in a:
    sq = pow((i - mean),2)
    sum += sq
  columns = a.shape[0]
  var = sum/columns
  stdd = sqrt(var)
  print(stdd)
a = np.array([1,2,3,4,5,6,7])
std(a)
np.std(a)


2.0


np.float64(2.0)