# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [ ]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [ ]:
import numpy as np
array = np.random.uniform(size=(10,10))
print(array)
array.mean()

[[0.54625777 0.75417752 0.13755163 0.24140922 0.13940651 0.90750972
  0.42529318 0.21771596 0.61848007 0.44610769]
 [0.10982467 0.55080097 0.5541078  0.50958522 0.85187154 0.53556592
  0.57395501 0.10471168 0.82344753 0.88047101]
 [0.38779913 0.97610579 0.87568729 0.26685975 0.55920807 0.58122041
  0.35253118 0.10838921 0.21007633 0.45023518]
 [0.90511926 0.07933332 0.90404668 0.66069213 0.90481406 0.71100884
  0.86766162 0.75537154 0.72913157 0.7285638 ]
 [0.6157169  0.35294191 0.95241857 0.33077654 0.92030645 0.18846884
  0.5472134  0.91218627 0.28256019 0.22408191]
 [0.30302566 0.7914427  0.23050177 0.45358049 0.90530071 0.28890352
  0.07469783 0.32309439 0.35245322 0.07762173]
 [0.23661869 0.80008977 0.76737113 0.56364424 0.38788349 0.93208585
  0.37147761 0.96401865 0.61178166 0.80761187]
 [0.12325018 0.68451333 0.74140381 0.20089501 0.96548914 0.00126256
  0.66743035 0.08580112 0.34825233 0.68465143]
 [0.94348492 0.00909556 0.15715236 0.20013303 0.48925    0.77747711
  0.81016968

0.5253120102406992

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = a + 5
c = a + 10
x = np.stack((a, b, c), axis=1)
print(x)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [ ]:
import numpy as np
def array(m,n):
  x = np.zeros((m,n), dtype=int)
  x[0,:] = 1
  x[-1,:] = 1
  x[1:-1,0] = 1
  x[1:-1,-1] = 1
  return x
array(4,5)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [ ]:
import numpy as np
angles = np.array([0, np.pi/12, np.pi/6, np.pi/4, np.pi/3, np.pi*5/12, np.pi/2])
sine = np.sin(angles)
cosine = np.cos(angles)
tangent = np.tan(angles)
inv_sine = np.arcsin(sine)
inv_cosine = np.arccos(cosine)
inv_tangent = np.arctan(tangent)
print(sine)
print(cosine)
print(tangent)
print(inv_sine)
print(inv_cosine)
print(inv_tangent)


[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [ ]:
import numpy as np
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
x_new = np.diff(x)
for a in x_new:
  print(a)

-2
3
3
3
-4
6
2
-9


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [ ]:
import numpy as np
sample_txt = np.loadtxt("https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt")
print(np.histogram(sample_txt))



(array([ 6, 23, 52, 37, 16, 14, 13, 13, 13, 13]), array([-30.58842789, -17.6295851 ,  -4.67074231,   8.28810048,
        21.24694327,  34.20578606,  47.16462884,  60.12347163,
        73.08231442,  86.04115721,  99.        ]))


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(np.std(a))
def stdfunc(z):
  x = (z - ((z.sum())/z.size))**2
  print(np.sqrt(((x.sum())/z.size)))
stdfunc(a)




1.4142135623730951
1.4142135623730951
