# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [1]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [3]:
arr=10*np.random.random_sample((10,10))
print (arr)
mean=np.mean(arr)
print (mean)

[[4.19656981 3.19917134 7.47713391 3.33053411 0.03971033 3.09614103
  6.53061567 0.94303491 8.52208268 7.39992575]
 [7.22666069 3.06778704 3.065144   2.8623451  7.64651599 2.45945134
  3.80411882 7.42418112 0.27208239 6.67004748]
 [1.64272149 3.03101299 6.79435939 1.79080355 0.98219348 8.74000816
  2.84886808 0.87634385 3.3289655  2.13558226]
 [4.23473677 2.67301804 1.61410164 4.67038161 0.84533835 3.80630246
  1.49555296 6.67345417 2.63939564 0.28389824]
 [3.90869757 2.86226773 8.70030535 6.4862441  9.42090712 8.44605802
  4.98639706 2.81529944 8.06122166 6.71982378]
 [0.7682826  1.30495419 6.91756752 8.79448444 9.33485526 1.67019141
  1.84464153 5.81608196 8.96760185 1.74503251]
 [9.6767385  2.30798559 9.27107857 1.9694263  6.25865059 1.4019748
  9.76909751 5.93601087 5.82727822 1.9158659 ]
 [1.15632163 5.08007843 3.44552021 1.84049942 1.87911153 6.97728702
  7.81428507 7.88629809 7.85760274 7.91556138]
 [1.96362571 7.17177513 9.82140062 6.08307522 4.9820189  9.95953654
  2.12174712 

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [10]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr2= (np.stack(np.array_split(arr1,3),axis=1))
print (arr2)
fa=[False, True, False, True, False]
arr3= arr2[fa]
print (arr3)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [38]:
def create_border_array(r, c):
    array = np.ones((r, c), dtype=int)
    array[1:-1, 1:-1] = 0
    return array
r,c=5,4
print(create_border_array(r,c))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [23]:
arr1=np.array([0,15,30,45,60,75,90])
x=np.deg2rad(arr1)
arr2=np.sin(x)
print (arr2)
arr3=np.cos(x)
print (arr3)
arr4=np.tan(x)
print (arr4)
a1=np.arcsin(arr2)
print (a1)
a2=np.arccos(arr3)
print (a2)
a3=np.arctan(arr4)
print (a3)
print (x)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]
[0.         0.26179939 0.52359878 0.78539816 1.04719755 1.30899694
 1.57079633]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [27]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
d= np.diff(x)
print (d)
f=np.absolute(d)
print (f)

[-2  3  3  3 -4  6  2 -9]
[2 3 3 3 4 6 2 9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [36]:
def stdd(a):
  m=np.mean(a)
  s=0.0
  for i in range(len(a)):
    s=s+pow((a[i]-m),2)
  x=s/(len(a))
  st=np.sqrt(x)
  return st

arr=np.array([1,2,3,4,5,6])
print (arr)
print(stdd(arr))
print(np.std(arr))

[1 2 3 4 5 6]
1.707825127659933
1.707825127659933
