# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [30]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [5]:
arr=np.random.random_sample((10,10))*10
avg= np.mean(arr)

## Q2

Create the array:
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [16]:
arr = np.arange(1, 16).reshape(5, 3, order='F')
print(arr)
arr1= arr[[1,3],:]
print(arr1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]


## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [21]:
x=int(input())
y=int(input())
arr=np.full((x,y),0)
arr[0,:]=1
arr[-1,:]=1
arr[:,0]=1
arr[:,-1]=1
print(arr)

2
2
[[1 1]
 [1 1]]


## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [28]:
arr=np.arange(0,91,15)
np.array(arr,ndmin=2)
print("Angles=",arr)
rad=np.radians(arr)
sin=np.sin(rad)
cos=np.cos(rad)
tan=np.tan(rad)
asin=np.degrees(np.arcsin(sin))
acos=np.degrees(np.arccos(cos))
atan=np.degrees(np.arctan(tan))
print("SIN=",sin)
print("COS=",cos)
print("TAN=",tan)
print("SIN INVERSE=",asin)
print("COS INVERSE=",acos)
print("TAN INVERSE=",atan)



Angles= [ 0 15 30 45 60 75 90]
SIN= [0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
COS= [1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
TAN= [0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]
SIN INVERSE= [ 0. 15. 30. 45. 60. 75. 90.]
COS INVERSE= [ 0. 15. 30. 45. 60. 75. 90.]
TAN INVERSE= [ 0. 15. 30. 45. 60. 75. 90.]


## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [38]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
print(np.diff(x))

[-2  3  3  3 -4  6  2 -9]


## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [64]:
text = np.loadtxt("https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt")
count,binedges = np.histogram(text)
for i in range(len(count)):
    bincenter=(binedges[i] + binedges[i+1]) / 2
    print("Bin center:{:20%}, Count:{:20%}".format(bincenter,count[i]))

Bin center:       -2410.900649%, Count:         600.000000%
Bin center:       -1115.016370%, Count:        2300.000000%
Bin center:         180.867908%, Count:        5200.000000%
Bin center:        1476.752187%, Count:        3700.000000%
Bin center:        2772.636466%, Count:        1600.000000%
Bin center:        4068.520745%, Count:        1400.000000%
Bin center:        5364.405024%, Count:        1300.000000%
Bin center:        6660.289303%, Count:        1300.000000%
Bin center:        7956.173582%, Count:        1300.000000%
Bin center:        9252.057861%, Count:        1300.000000%


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:

$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [63]:
def customstd(arr):
    sum=0
    avg=np.mean(arr)
    sum=np.sum((arr-avg)**2)
    variance=sum/(len(arr))
    std=np.sqrt(variance)
    print(std)
arr1=np.array([123,152,69,73,465])
print("np.std :",np.std(arr1))
customstd(arr1)

np.std : 147.6233043933105
147.6233043933105
